### PR TITLE
Fix: Example networks

### LINKED ISSUE #95: Fix and QA on example notebooks
Notebooks are broken since they have not been tested together with the rest of the code until now... Need to fix these. We will include them in automatic testing when this is done. For now only the test_*-notebooks are tested.

### PR DESCRIPTION
**Pull request by HaraldGSvendsen**
# Pull Request

### WHAT

Example Jupyter notebooks

### WHY

Notebooks fail when run

### HOW

Updated notebooks in line with recent changes elsewhere in the code.

## Type of change

Updated notebooks in line with recent changes elsewhere in the code.

- [x] Bug fix - Requires bug fix version bump. e.g. from v1.0.0 to v1.0.1

## What to test/verify

*Any specific way to test/verify the change? (ie an update to readme or other documentation would be sufficient)*

## Checklist:

- [x] :tada: This PR closes #95 .
- [x] :scroll: I have broken down my PR into the following tasks:
   - [x] Fix so notebooks run without error
   - [x] Improve quality as examples for new users
- [x] :robot: I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.
- [x] :book: I have considered adding a new entry in `CHANGES.md`.
- [x] :books: I have considered updating the documentation in `README.md`, `userguide.md` or `docs/oogeso_manual.tex`.

### CODE REVIEW

**Comment by HaraldGSvendsen** [comment]
Tests work locally on my computer

**Comment by mortendaehli** [comment]
> 

The relative file location is different. You should use Path(oogeso.__file__).parent.parent / "examples" / "ame of file.yml" or something like that.

We have done it in some of the other tests.

**Comment by mortendaehli** [comment]
> Tests work locally on my computer

Try do something like this to get the correct paths both locally and in GitHub Actions: https://github.com/oogeso/oogeso/blob/master/tests/conftest.py#L11-L20

**Comment by HaraldGSvendsen** [comment]
Seems to me this is happening: The notebooks are tested on the docker image, which is pushed from the master branch. So changes to these will not be visible until merged into master.

**Comment by mortendaehli** [comment]
Tried to rebase this one, but I was unsuccessful. Let me know what you want to do. I can fix the path issue when it is ready :)

**Pull request merged**
