### PR TITLE
build!: Add support for Python 3.11

### PR DESCRIPTION
**Pull request by mortendaehli**
Updating relevant dependencies.
Switched pyarrow for fastparquet due
to build issues. Remove Python 3.7
support due to missing Scipy support.

BREAKING CHANGE: 'no longer support Python 3.7'

Blocked by pyomo. Waiting for new release: https://github.com/Pyomo/pyomo/pull/2596

### CODE REVIEW

**Comment by mortendaehli** [comment]
Pyomo has a pending Python 3.11 PR: https://github.com/Pyomo/pyomo/pull/2596

Need to wait for this before we upgrade.

**Comment by blnicho** [comment]
@mortendaehli the next Pyomo release is scheduled for November 21

**Review by HaraldGSvendsen — APPROVED** [review]
OK!

**Comment by mortendaehli** [comment]
@HaraldGSvendsen, do you understand why the test suddenly fail in test_electricalsystem.py?

**Comment by HaraldGSvendsen** [comment]
No, I dont understand the fail in test_electricalsystem.py - I'll look into it.

**Comment by HaraldGSvendsen** [comment]
Should be ready to merge

**Pull request merged**
